name: demo-environment
channels:
  - conda-forge
dependencies:
  - python==3.11.11
  - numpy
  - matplotlib
  - pandas==1.5.3
  - xarray
  - seaborn
  - scipy
  - netcdf4
  - cartopy
  - rioxarray
  - pycaret
  - mlflow==2.16.0